package lk.ijse.Util;

public enum TextField {
//    NAME, ADDRESS, TEL, STATUS, QTY, LBLNAME, FABSIZE, DESCRIPTION, PRICE, PRICEDOT, EMPID, EID, SUPID, UID, FABID, ANY,  EMAIL
    NAME, TEL, PRICE, DURATION, ADDRESS, PRICEDOT,INTID

}